using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class test3_sub : MonoBehaviour
{
    //—ûK–â‘è1
    //•Ï”x‚É10.5A•Ï”y‚É3.14
    //ŒvZŒ‹‰Ê‚ğ“ü‚ê‚é•Ï”sum‚ğì¬
    //x + y = ZZ(ŒvZ‚µ‚½sum‚Ì’l)
    //x - y = ZZ(ŒvZ‚µ‚½sum‚Ì’l)
    //x * y = ZZ(ŒvZ‚µ‚½sum‚Ì’l)
    //x / y = ZZ(ŒvZ‚µ‚½sum‚Ì’l)
    //x % y = ZZ(ŒvZ‚µ‚½sum‚Ì’l)
    //‚Æ‚È‚é‚æ‚¤ADebug.log‚ğg‚Á‚Ä•\¦‚·‚é

    //int + float‚ÌŒvZ‚ÍŸè‚Éfloat‚É‚È‚é
    //‚±‚Ì‚æ‚¤‚ÉŸè‚ÉŒ^‚ª•ÏX‚³‚ê‚é‚±‚Æ‚ğ
    //ˆÃ–Ù‚ÌŒ^•ÏŠ·‚Æ‚¢‚¤

    float x = 10.5f;
    float y = 3.14f;
    float sum;
    // Start is called before the first frame update
    void Start()
    {
        sum = x + y;
        Debug.Log("x + y ="  + sum);

        sum = x - y; 
        Debug.Log("x - y =" + sum);

        sum = x * y;
        Debug.Log("x * y =" + sum);
        sum = x / y;
        Debug.Log("x / y =" + sum);

        sum = x % y;
        Debug.Log("x % y =" + sum);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
