using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.AI;
using static Unity.Collections.Unicode;

public class test_20_sub : MonoBehaviour
{
    [Serialize] public int m = 1;

    // ‰Û‘è20
    // 1‚©‚ç12‚Ì’l‚ðŽ‚Â—ñ‹“Œ^AMonth‚ðì¬
    // 1...January, 2...February..‚Æ‚¢‚Á‚½‚æ‚¤‚ÈŒ^‚ðì‚é
    enum Month
    {
        none,
        January,
        February,
        March,
        April,
        May,
        June,
        July,
        August,
        September,
        October,
        November,
        December,
    };
    Month x = Month.May;

    // intŒ^‚Ì•Ï”x‚ðì¬‚µAŽ©•ª‚Ì’a¶ŒŽ‚ðMonthŒ^‚Ì—ñ‹“Žq‚Å
    // ƒLƒƒƒXƒg‚ð—p‚¢‚Ä‘ã“ü
    // Debug.log‚Åx‚ð•\Ž¦
    // •\Ž¦—áj’a¶ŒŽ‚Í10

    // ®”Œ^‚Ì•Ï”m‚ÉD‚«‚È®”‚ð“ü—Í‚µA
    // ‚»‚ÌŒŽ‚ðMonthŒ^‚Ì—ñ‹“Žq‚É•ÏŠ·‚µ‚Ä•\Ž¦‚·‚é
    // ‚È‚¨A‚O‚â‚X‚X‚Æ‚¢‚Á‚½’l‚ª“ü—Í‚³‚ê‚½ê‡A
    // –³Œø‚È’l‚Å‚·‚Æ•\Ž¦‚·‚é
    // •\Ž¦—áj
    // m‚ª0‚Ìê‡„–³Œø‚È’l‚Å‚·
    // m‚ª2‚Ìê‡„February
    string[] MonthTable =
    {
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",

    };
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log($"’a¶“ú‚Í{(int)x}ŒŽ");


        if (m > 0 && m <= 12)
        {
            Month month = (Month)(int)m;
            Debug.Log(month);
        }
        else
        {
            Debug.Log($"{m}‚Í–³Œø‚È’l‚Å‚·");
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
